import chalk from 'chalk';
import figlet from 'figlet';

// Display "Notes Manager" on installation (after npm install @pujan2412/notes-manager-cli)
figlet.text("Nman", { font: "Univers", horizontalLayout: 'fitted'}, (error, data) => {
  if (error) {
    console.log("Something went wrong with figlet..."); // Log an error message to the console if something went wrong
    return;
  }

  // If no error, log the ASCII art generated by 'figlet' to the console
  console.log(chalk.greenBright.bold(data));
  console.log(chalk.blueBright("\nThanks For Installing Nman 🚀\n"));
});